version: '3.8'

services:
  security-service:
    build:
      context: .
      dockerfile: ./backend/services/security-service/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=kngmdapg14
      - TOKEN_EXPIRATION=1h
    depends_on:
      - firebase

  customer-service:
    build:
      context: .
      dockerfile: ./backend/services/customer-service/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    depends_on:
      - firebase

  zone-service:
    build:
      context: .
      dockerfile: ./backend/services/zone-service/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
    depends_on:
      - firebase

  distributor-service:
    build:
      context: .
      dockerfile: ./backend/services/distributor-service/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: production
    depends_on:
      - firebase

  order-service:
    build:
      context: .
      dockerfile: ./backend/services/order-service/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
    depends_on:
      - firebase

  product-service:
    build:
      context: .
      dockerfile: ./backend/services/product-service/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "3006:3006"
    environment:
      NODE_ENV: production
    depends_on:
      - firebase

  firebase:
    image: google/cloud-sdk:latest
    volumes:
      - ./firebase:/root/.config/firebase
