// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOof3KPaGtk4UIJh9l4m93a0kOUcxiWDE',
    appId: '1:137181404242:web:f21f87a5aa69430899d38b',
    messagingSenderId: '137181404242',
    projectId: 'appzohar-6e93c',
    authDomain: 'appzohar-6e93c.firebaseapp.com',
    databaseURL: 'https://appzohar-6e93c-default-rtdb.firebaseio.com',
    storageBucket: 'appzohar-6e93c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQ814lderxkVTMdconq6ln6JWVW4qOUA',
    appId: '1:137181404242:android:50b3cd7ad5e9c2bc99d38b',
    messagingSenderId: '137181404242',
    projectId: 'appzohar-6e93c',
    databaseURL: 'https://appzohar-6e93c-default-rtdb.firebaseio.com',
    storageBucket: 'appzohar-6e93c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ALTUWtqHCSfXmLOqz0h8bAfELGH53-o',
    appId: '1:137181404242:ios:d68073485e86820799d38b',
    messagingSenderId: '137181404242',
    projectId: 'appzohar-6e93c',
    databaseURL: 'https://appzohar-6e93c-default-rtdb.firebaseio.com',
    storageBucket: 'appzohar-6e93c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ALTUWtqHCSfXmLOqz0h8bAfELGH53-o',
    appId: '1:137181404242:ios:d68073485e86820799d38b',
    messagingSenderId: '137181404242',
    projectId: 'appzohar-6e93c',
    databaseURL: 'https://appzohar-6e93c-default-rtdb.firebaseio.com',
    storageBucket: 'appzohar-6e93c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAheOyPaixjrMNJOpPQOqD1DGwIyiFBru0',
    appId: '1:137181404242:web:4553ba81529c609d99d38b',
    messagingSenderId: '137181404242',
    projectId: 'appzohar-6e93c',
    authDomain: 'appzohar-6e93c.firebaseapp.com',
    databaseURL: 'https://appzohar-6e93c-default-rtdb.firebaseio.com',
    storageBucket: 'appzohar-6e93c.firebasestorage.app',
  );
}
